[package]
name = "workd-client"
description = "Client for talking to workd over SSH or locally."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
workd-core.workspace = true
anyhow.workspace = true
toml.workspace = true
workd-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
