//! Typed identifiers.
//!
//! Ids are short random strings with a type prefix (`ws_`, `ses_`, `exec_`).
//! They are generated by the daemon that owns the entity and are unique enough
//! to be used across hosts without coordination.

use std::fmt;

use rand::Rng;
use serde::{Deserialize, Serialize};

const ALPHABET: &[u8] = b"0123456789abcdefghjkmnpqrstvwxyz";
const RANDOM_LEN: usize = 10;

fn random_suffix() -> String {
    let mut rng = rand::rng();
    (0..RANDOM_LEN)
        .map(|_| ALPHABET[rng.random_range(0..ALPHABET.len())] as char)
        .collect()
}

macro_rules! id_type {
    ($(#[$meta:meta])* $name:ident, $prefix:literal) => {
        $(#[$meta])*
        #[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $name(String);

        impl $name {
            pub const PREFIX: &'static str = $prefix;

            pub fn generate() -> Self {
                Self(format!("{}{}", $prefix, random_suffix()))
            }

            pub fn as_str(&self) -> &str {
                &self.0
            }

            /// Whether `s` looks like an id of this type (used to disambiguate
            /// ids from human-chosen names).
            pub fn looks_like(s: &str) -> bool {
                s.starts_with($prefix)
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl From<String> for $name {
            fn from(s: String) -> Self {
                Self(s)
            }
        }

        impl From<&str> for $name {
            fn from(s: &str) -> Self {
                Self(s.to_owned())
            }
        }
    };
}

id_type!(
    /// Identifies a [`crate::Workspace`].
    WorkspaceId,
    "ws_"
);
id_type!(
    /// Identifies a [`crate::Session`] — a durable logical activity.
    SessionId,
    "ses_"
);
id_type!(
    /// Identifies an [`crate::Execution`] — one concrete process run of a session.
    ExecutionId,
    "exec_"
);
id_type!(
    /// Identifies an [`crate::Attention`] item.
    AttentionId,
    "att_"
);
id_type!(
    /// Identifies a [`crate::feature::Feature`] — a piece of product work.
    FeatureId,
    "ft_"
);
id_type!(
    /// Identifies a [`crate::feature::Task`] within a feature's plan.
    TaskId,
    "tk_"
);
id_type!(
    /// Identifies a [`crate::feature::Run`] — one agent run working on a task.
    RunId,
    "run_"
);
id_type!(
    /// Identifies a [`crate::feature::Message`] in a feature's conversation.
    MessageId,
    "msg_"
);
id_type!(
    /// Identifies a [`crate::feature::DecisionRequest`].
    DecisionId,
    "dec_"
);
id_type!(
    /// Identifies a piece of [`crate::feature::Evidence`].
    EvidenceId,
    "ev_"
);
id_type!(
    /// Identifies a [`crate::conversation::Conversation`] — a coding agent's
    /// durable context (D-055).
    ConversationId,
    "conv_"
);
id_type!(
    /// Identifies a [`crate::conversation::Turn`] — one accepted input and
    /// the work that followed.
    TurnId,
    "turn_"
);
id_type!(
    /// Identifies a [`crate::conversation::ToolRecord`] — one tool call.
    ToolCallId,
    "tool_"
);
id_type!(
    /// Identifies a [`crate::conversation::Block`] of a message.
    BlockId,
    "blk_"
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_ids_have_prefix_and_are_unique() {
        let a = WorkspaceId::generate();
        let b = WorkspaceId::generate();
        assert!(a.as_str().starts_with("ws_"));
        assert_eq!(a.as_str().len(), 3 + RANDOM_LEN);
        assert_ne!(a, b);
        assert!(ExecutionId::looks_like(ExecutionId::generate().as_str()));
    }
}
